### PR TITLE
Added option to set the custom TextView ID

### PR DESCRIPTION
**Pull request by douglasjunior**
- added option to set the custom TextView ID in method withCustomView() (updated javadoc) ([here](https://github.com/sephiroth74/android-target-tooltip/commit/01b5b18cf435eb47bb9aaa851205b16a1f9e402f#diff-0f8cc6eb0b4776e223bacd7ee2a381c6R1552) and [here](https://github.com/sephiroth74/android-target-tooltip/commit/01b5b18cf435eb47bb9aaa851205b16a1f9e402f#diff-0f8cc6eb0b4776e223bacd7ee2a381c6R1560))
- renamed mTextResId to mCustomResId ([here](https://github.com/sephiroth74/android-target-tooltip/commit/01b5b18cf435eb47bb9aaa851205b16a1f9e402f#diff-0f8cc6eb0b4776e223bacd7ee2a381c6L250))
- added mCustomTextViewId property ([here](https://github.com/sephiroth74/android-target-tooltip/commit/01b5b18cf435eb47bb9aaa851205b16a1f9e402f#diff-0f8cc6eb0b4776e223bacd7ee2a381c6R253))
- added public getContextView() to return the tooltip View ([here](https://github.com/sephiroth74/android-target-tooltip/commit/01b5b18cf435eb47bb9aaa851205b16a1f9e402f#diff-0f8cc6eb0b4776e223bacd7ee2a381c6R215))
- fixed problem reported in #44 , now the arrow is generated in mView instead of mTextView ([here](https://github.com/sephiroth74/android-target-tooltip/commit/01b5b18cf435eb47bb9aaa851205b16a1f9e402f#diff-0f8cc6eb0b4776e223bacd7ee2a381c6L812) and [here](https://github.com/sephiroth74/android-target-tooltip/commit/01b5b18cf435eb47bb9aaa851205b16a1f9e402f#diff-0f8cc6eb0b4776e223bacd7ee2a381c6L814) and [here](https://github.com/sephiroth74/android-target-tooltip/commit/01b5b18cf435eb47bb9aaa851205b16a1f9e402f#diff-0f8cc6eb0b4776e223bacd7ee2a381c6L816))
- changed target that receives the animation to TooltipViewImpl instead of "mTextView" ([here](https://github.com/sephiroth74/android-target-tooltip/commit/01b5b18cf435eb47bb9aaa851205b16a1f9e402f#diff-0f8cc6eb0b4776e223bacd7ee2a381c6L1213) and [here](https://github.com/sephiroth74/android-target-tooltip/commit/01b5b18cf435eb47bb9aaa851205b16a1f9e402f#diff-0f8cc6eb0b4776e223bacd7ee2a381c6L1217))

Now, is possible to use any custom view, and the arrow will not appear only if "replaceBackground = true" or "withArrow = false"

Please, look to this PR and let me know if something is wrong.

### CODE REVIEW

**Comment by sephiroth74** [comment]
Can you split the changes into multiple pull requests? So we can go through each one separately

**Comment by douglasjunior** [comment]
The changes are dependent :(

1. First I added the option for set the TextView ID.
2. This caused problems with the animation, because only the `TextView` was animated. So I changed to animate full TooltipViewImpl.
3. If the `background` of the `layout` has the same color as the `TextView`, the arrow disappears. Because the arrow was created in `TextView`. So I changed to create in parent `layout` (`mView`). 
4. I need retrieve the `views` out (via findViewById), so I created the `getContentView`

I dont know how I could split this. What do you think?

**Comment by sephiroth74** [comment]
Ah ok, I thought they were separate features.
Why should you be able to specify the text id? I don't see any value on that.

**Comment by douglasjunior** [comment]
In my case, I use a standard for naming IDs (only for good practice). However, if the user does not specify keeps `android.R.id.text1`

But the biggest problems were:

- The animation happen only in TextView. If I put a custom layout with a TextView and a button, only the TextView would move, the button does not move.
- And the problem with the Arrow, which also was known, and was explained in the documentation.

Please, feel free to evaluate the PR. If these changes are not interesting, I can use my Fork for now.

**Comment by sephiroth74** [comment]
I think you should keep the fixed id for the textview. Give too much freedom to devs is not always a good thing and can just add more complexity to the app. Anyway, I don't have time now for evaluating the PR cause I'm leaving for vacation, but I'll do as soon I'll go back next week. thank you.

**Comment by douglasjunior** [comment]
I appreciate your attention.

I'm a bit of urgency, I had to create my [own implementation](https://github.com/douglasjunior/android-simple-tooltip). :smile: 

Sorry for taking your time. I'll look at your library again in the future.

Thank you

**Pull request closed without merging**
