### PR TITLE
Adjust arrow's position follow style attribute

### PR DESCRIPTION
**Pull request by Nghicv**
Add attribute `ttlm_arrowPositionRatio` to allow adjusting the arrow's position.

### CODE REVIEW

**Review by LimeAdrian — APPROVED** [review]

**Comment by ImYoungUn** [comment]
@LimeAdrian  @Nghicv Do you know when it will be merged?

**Comment by Nghicv** [comment]
@ImYoungUn Sorry, I don't know.

**Comment by BelooS** [comment]
@LimeAdrian any updates on this?

**Comment by samuelchou** [comment]
There're conflicts now.
I'm also looking forward to merge! 💪

**Comment by Nghicv** [comment]
Hi @sephiroth74 , Could you please review the PR?

**Comment by Nghicv** [comment]
I closed the PR because I don't see any responses from the author.

**Pull request closed without merging**
